In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
streaming_df = pd.read_json('../data/StreamingHistory0.json')

In [129]:
streaming_df['count'] = 1
streaming_df.head(10)

,endTime,artistName,trackName,msPlayed,count
0,2021-10-26 23:02,Daniel Caesar,Transform (feat. Charlotte Day Wilson),277984,1
1,2021-10-28 00:36,Nia Sultana,Coconut Water,25836,1
2,2021-10-28 00:36,Nia Sultana,Positions,146823,1
3,2021-10-28 00:40,Wizkid,Essence (feat. Tems),234590,1
4,2021-10-28 00:42,Nija,Finesse,129850,1
5,2021-10-28 00:45,Femme It Forward,What You Deserve,175702,1
6,2021-10-28 01:02,Bathe,Sundress,3100,1
7,2021-10-28 01:02,Tone Stith,Do I Ever (feat. Chris Brown),166817,1
8,2021-10-28 01:04,Sonder,Nobody But You,165440,1
9,2021-10-28 01:27,Adele,Easy On Me,120624,1

In [4]:
streaming_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3815 entries, 0 to 3814
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   endTime     3815 non-null   object
 1   artistName  3815 non-null   object
 2   trackName   3815 non-null   object
 3   msPlayed    3815 non-null   int64
 4   count       3815 non-null   int64
dtypes: int64(2), object(3)
memory usage: 149.1+ KB

In [5]:
streaming_df.isnull().sum()

endTime       0
artistName    0
trackName     0
msPlayed      0
count         0
dtype: int64

In [6]:
streaming_df.describe()

           msPlayed   count
count  3.815000e+03  3815.0
mean   1.531290e+05     1.0
std    1.344888e+05     0.0
min    0.000000e+00     1.0
25%    4.008950e+04     1.0
50%    1.683870e+05     1.0
75%    2.179900e+05     1.0
max    3.822727e+06     1.0

In [7]:
streaming_df.groupby('trackName')['count'].count().sort_values(ascending=False).head(20)

trackName
CPR                                 89
Later                               86
Lose Control                        71
Coming Home                         71
Session 32                          62
One Right Now (with The Weeknd)     61
telepatía                           60
On It                               57
In the Air                          55
Hometown Glory                      55
You Can't Save Me                   52
Remember Me                         52
Essence (feat. Tems)                50
Bad Habit                           50
Positions                           47
Waiting For (feat. Jamila Woods)    46
Moment                              43
I Drink Wine                        40
Better Than                         30
Not Another Love Song               29
Name: count, dtype: int64

In [11]:
streaming_df.groupby('artistName')['count'].count().sort_values(ascending=False).head(20)

artistName
Adele               207
Summer Walker       197
Beyoncé             159
Leon Bridges        102
Pinegrove            91
L.A.B.               90
Jazmine Sullivan     89
emawk                88
MEDUZA               78
Steve Lacy           70
Kali Uchis           68
Free Nationals       68
Post Malone          63
Nia Sultana          59
Lake Street Dive     57
SiR                  57
Wizkid               54
UMI                  53
rum.gold             48
Matt Corby           48
Name: count, dtype: int64

In [16]:
#678 different artists
artists = streaming_df['artistName'].unique()
len(streaming_df['artistName'].unique())

678

In [ ]:
#Pull artist ID's 
#Use Artist IDs to get the genre associated with each artist
#Pull other artists within a given genre

In [8]:
#load kaggle data
kaggle_df = pd.read_csv('../data/data.csv')
kaggle_df.head()

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,['Frank Parker'],0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,['Phil Regan'],0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665

In [9]:
kaggle_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 170653 entries, 0 to 170652
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   valence           170653 non-null  float64
 1   year              170653 non-null  int64
 2   acousticness      170653 non-null  float64
 3   artists           170653 non-null  object
 4   danceability      170653 non-null  float64
 5   duration_ms       170653 non-null  int64
 6   energy            170653 non-null  float64
 7   explicit          170653 non-null  int64
 8   id                170653 non-null  object
 9   instrumentalness  170653 non-null  float64
 10  key               170653 non-null  int64
 11  liveness          170653 non-null  float64
 12  loudness          170653 non-null  float64
 13  mode              170653 non-null  int64
 14  name              170653 non-null  object
 15  popularity        170653 non-null  int64
 16  release_date      170653 non-null  object
 17  speechiness       170653 non-null  float64
 18  tempo             170653 non-null  float64
dtypes: float64(9), int64(6), object(4)
memory usage: 24.7+ MB

In [10]:
kaggle_df2 = pd.read_csv('../data/data_by_genres.csv')
kaggle_df2.head()

,mode,genres,acousticness,danceability,duration_ms,energy,instrumentalness,liveness,loudness,speechiness,tempo,valence,popularity,key
0,1,21st century classical,0.979333,0.162883,1.602977e+05,0.071317,0.606834,0.361600,-31.514333,0.040567,75.336500,0.103783,27.833333,6
1,1,432hz,0.494780,0.299333,1.048887e+06,0.450678,0.477762,0.131000,-16.854000,0.076817,120.285667,0.221750,52.500000,5
2,1,8-bit,0.762000,0.712000,1.151770e+05,0.818000,0.876000,0.126000,-9.180000,0.047000,133.444000,0.975000,48.000000,7
3,1,[],0.651417,0.529093,2.328809e+05,0.419146,0.205309,0.218696,-12.288965,0.107872,112.857352,0.513604,20.859882,7
4,1,a cappella,0.676557,0.538961,1.906285e+05,0.316434,0.003003,0.172254,-12.479387,0.082851,112.110362,0.448249,45.820071,7

In [39]:
kaggle_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2973 entries, 0 to 2972
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   mode              2973 non-null   int64
 1   genres            2973 non-null   object
 2   acousticness      2973 non-null   float64
 3   danceability      2973 non-null   float64
 4   duration_ms       2973 non-null   float64
 5   energy            2973 non-null   float64
 6   instrumentalness  2973 non-null   float64
 7   liveness          2973 non-null   float64
 8   loudness          2973 non-null   float64
 9   speechiness       2973 non-null   float64
 10  tempo             2973 non-null   float64
 11  valence           2973 non-null   float64
 12  popularity        2973 non-null   float64
 13  key               2973 non-null   int64
dtypes: float64(11), int64(2), object(1)
memory usage: 325.3+ KB

In [27]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
cid = "bec8ed6d2e4c4623869edd14b310b1eb"
secret = "dd390053697a4cad874554c022b5db03"
client_credentials_manager = SpotifyClientCredentials(client_id=cid, client_secret=secret)
sp = spotipy.Spotify(client_credentials_manager = client_credentials_manager)

In [71]:
artist_name = []
artist_id = []
track_name = []
popularity = []
track_id = []

In [112]:
streaming_df.head(10)

,endTime,artistName,trackName,msPlayed,count
0,2021-10-26 23:02,Daniel Caesar,Transform (feat. Charlotte Day Wilson),277984,1
1,2021-10-28 00:36,Nia Sultana,Coconut Water,25836,1
2,2021-10-28 00:36,Nia Sultana,Positions,146823,1
3,2021-10-28 00:40,Wizkid,Essence (feat. Tems),234590,1
4,2021-10-28 00:42,Nija,Finesse,129850,1
5,2021-10-28 00:45,Femme It Forward,What You Deserve,175702,1
6,2021-10-28 01:02,Bathe,Sundress,3100,1
7,2021-10-28 01:02,Tone Stith,Do I Ever (feat. Chris Brown),166817,1
8,2021-10-28 01:04,Sonder,Nobody But You,165440,1
9,2021-10-28 01:27,Adele,Easy On Me,120624,1

In [146]:
artist = []
artist_id = []
genres = []
artist_popularity= []
followers = []

In [154]:
for i in streaming_df['artistName'][3000:]:
    results = sp.search(q=f'artist: {i}', type='artist', limit=1)
    for i, t in enumerate(results['artists']['items']):
        artist.append(t['name'])
        artist_id.append(t['id'])
        genres.append(t['genres'])
        artist_popularity.append(t['popularity'])
        followers.append(t['followers']['total'])

In [166]:
check = []
for name in streaming_df['artistName']:
    if name not in artist:
        check.append(name)

In [249]:
spotify_api = pd.DataFrame(artist)
spotify_api['artist_id'] = artist_id
spotify_api['genres'] = genres
spotify_api['artist_popularity'] = artist_popularity
spotify_api['followers'] = followers
spotify_api.rename(columns = {0:'artistName'}, inplace = True)
spotify_api.head(10)

,artistName,artist_id,genres,artist_popularity,followers
0,Daniel Caesar,20wkVLutqVOYrc0kxFs7rA,"[canadian contemporary r&b, pop, r&b]",77,3538095
1,Nia Sultana,1L8An7RfJbMW7zBy2fE0Tz,"[alternative r&b, chill r&b, indie r&b]",43,17840
2,Nia Sultana,1L8An7RfJbMW7zBy2fE0Tz,"[alternative r&b, chill r&b, indie r&b]",43,17840
3,Wizkid,3tVQdUvClmAT7URs9V3rsp,"[afro dancehall, afropop, azonto, nigerian hip...",76,2790812
4,Nija,7f9KxQWD88MZrSY6jc0zoW,"[alternative r&b, indie r&b, pop r&b, r&b]",49,29689
5,Femme It Forward,3rw1MKkbLTZw46AqC7gRpH,"[alternative r&b, indie r&b]",36,11503
6,Bathe,3BBN1P1JNw0sSdYEdBkOZK,"[alternative r&b, chill r&b, experimental r&b,...",41,9045
7,Tone Stith,756t7CBmWLNYsshVtS6P44,"[alternative r&b, chill r&b, indie r&b, pop r&...",52,160666
8,Sonder,2ICR2m4hOBPhaYiZB3rnLW,[r&b],66,456251
9,Adele,4dpARuHxo51G3z768sgnrY,"[british soul, pop, pop soul, uk pop]",84,43304700

In [201]:
streaming_df.to_csv('../data/streaming_df.csv')
spotify_api.to_csv('../data/spotify_api.csv')

In [217]:
len(check)

197

In [230]:
name = []
id = []
genre = []
popularity = []
follower = []

for i in check:
    results = sp.search(q=f'artist: {i}', type='artist', limit=10)
    for i, t in enumerate(results['artists']['items']):
        name.append(t['name'])
        id.append(t['id'])
        genre.append(t['genres'])
        popularity.append(t['popularity'])
        follower.append(t['followers']['total'])

In [267]:
missing_api = pd.DataFrame(name)
missing_api['artist_id'] = id
missing_api['genres'] = genre
missing_api['artist_popularity'] = popularity
missing_api['followers'] = follower
missing_api.rename(columns = {0:'artistName'}, inplace = True)
missing_api.head(10)

,artistName,artist_id,genres,artist_popularity,followers
0,Sleeping With Sirens,3N8Hy6xQnQv1F1XCiyGQqA,"[metalcore, modern rock, pop emo, pop punk, ro...",65,2079982
1,SiR,3QTDHixorJelOLxoxcjqGx,"[alternative r&b, hip hop, indie soul, la pop,...",63,740498
2,Seori,2bWTIIQP9zaVc55RaMGu7e,"[k-pop, korean r&b]",55,220959
3,Sir Chloe,6rniTPs9zN26kYnkPdFl1U,"[indie pop, modern rock]",61,510669
4,Sirah,3oAazIwC0nAYkOKVQPUC38,[],54,17873
5,Sir Neville Marriner,6NUhQz7eAEsZvjEHTKHux9,"[classical performance, orchestral performance]",64,27855
6,Siqtruand,34nrdgWD7gZThWiwbFWsI3,[],31,10
7,Sir Simon Rattle,4GQwgdcDQwqtcHICjUNndp,"[choral, classical performance, orchestral per...",62,47358
8,Sahir,0dqT9B1Xej71qvAo8uE4Uh,"[reggaeton flow, trap boricua, trap latino]",43,19204
9,Sir Mix-A-Lot,3TQ9JTBI2n2hfo7aRONEYV,"[gangster rap, hip hop, hip house, old school ...",54,481535

In [233]:
check2 = []
for n in check:
    if n not in name:
        check2.append(n)

In [234]:
check2

['ELIZA',
 'FantasyPros - Fantasy Football Podcast',
 '2021 Wrapped',
 'BLEU',
 'The Joe Rogan Experience',
 'The Joe Rogan Experience',
 'The Pomp Podcast',
 'The Journal.',
 'The Mindset Mentor',
 'The Mindset Mentor',
 'The Mindset Mentor',
 'The Mindset Mentor',
 'The Mindset Mentor',
 'The Mindset Mentor',
 'The Mindset Mentor',
 'Focus/Study Music',
 'Girls']

In [281]:
spotify_api.drop_duplicates(subset = 'artist_id',inplace = True)
missing_api.drop_duplicates(subset = 'artistName', inplace = True)
spotify_df = pd.concat([spotify_api, missing_api])
spotify_df.drop_duplicates(subset = 'artistName', inplace = True)
spotify_df

In [296]:
final = pd.merge(streaming_df, spotify_df, how = "left", on = ['artistName', 'artistName'])
final.shape

(3815, 9)

In [297]:
final.isnull().sum()

endTime               0
artistName            0
trackName             0
msPlayed              0
count                 0
artist_id            17
genres               17
artist_popularity    17
followers            17
dtype: int64

In [298]:
final.dropna(inplace= True)

In [300]:
final

,endTime,artistName,trackName,msPlayed,count,artist_id,genres,artist_popularity,followers
0,2021-10-26 23:02,Daniel Caesar,Transform (feat. Charlotte Day Wilson),277984,1,20wkVLutqVOYrc0kxFs7rA,"[canadian contemporary r&b, pop, r&b]",77.0,3538095.0
1,2021-10-28 00:36,Nia Sultana,Coconut Water,25836,1,1L8An7RfJbMW7zBy2fE0Tz,"[alternative r&b, chill r&b, indie r&b]",43.0,17840.0
2,2021-10-28 00:36,Nia Sultana,Positions,146823,1,1L8An7RfJbMW7zBy2fE0Tz,"[alternative r&b, chill r&b, indie r&b]",43.0,17840.0
3,2021-10-28 00:40,Wizkid,Essence (feat. Tems),234590,1,3tVQdUvClmAT7URs9V3rsp,"[afro dancehall, afropop, azonto, nigerian hip...",76.0,2790812.0
4,2021-10-28 00:42,Nija,Finesse,129850,1,7f9KxQWD88MZrSY6jc0zoW,"[alternative r&b, indie r&b, pop r&b, r&b]",49.0,29689.0
...,...,...,...,...,...,...,...,...,...
3810,2022-10-27 23:26,The Pussycat Dolls,Don't Cha,3130,1,6wPhSqRtPu1UhRCDX5yaDJ,"[dance pop, girl group, pop, post-teen pop, uk...",68.0,5238891.0
3811,2022-10-27 23:26,PAMÉ,Fresh Water,2030,1,5ZSOXLTnZcSjdVCIdjnq03,[],28.0,2108.0
3812,2022-10-27 23:26,KAYTRANADA,What You Need,16440,1,6qgnBH6iDM91ipVXv28OMu,"[escape room, lgbtq+ hip hop]",69.0,1084031.0
3813,2022-10-27 23:26,Lizzo,2 Be Loved (Am I Ready),2100,1,56oDRnqbIiwx4mymNEv7dS,"[escape room, minnesota hip hop, pop, trap queen]",79.0,5109990.0
3814,2022-10-27 23:26,Beyoncé,BREAK MY SOUL,17640,1,6vWDO969PvNqNYHIOW5v0m,"[dance pop, pop, r&b]",87.0,32488815.0

In [ ]:
name = []
id = []
genre = []
popularity = []
follower = []

for i in final['track_name']:
    results = sp.search(q=f'artist: {i}', type='artist', limit=10)
    for i, t in enumerate(results['artists']['items']):
        name.append(t['name'])
        id.append(t['id'])
        genre.append(t['genres'])
        popularity.append(t['popularity'])
        follower.append(t['followers']['total'])

In [334]:
trackName = []
trackID = []

for a,t in list(final[['artistName', 'trackName']][:1000].itertuples(index=False, name=None)):
    results = sp.search(q="artist:" + a + " track:" + t, type="track", limit =1)
    for i, t in enumerate(results['tracks']['items']):
        trackName.append(t['name'])
        trackID.append(t['id'])

In [341]:
for a,t in list(final[['artistName', 'trackName']][3000:].itertuples(index=False, name=None)):
    results = sp.search(q="artist:" + a + " track:" + t, type="track", limit =1)
    for i, t in enumerate(results['tracks']['items']):
        trackName.append(t['name'])
        trackID.append(t['id'])

In [344]:
len(trackName)

4083

In [301]:
#next step I need the track get audio features (danceability, energy, acousticness, etc)
#I can pull this data using the search query/get track endpoint

In [59]:
# I am pulling the same 1k songs 10 times, I want to pull 10k different songs

In [67]:
len(pd.unique(track_name))

971

In [78]:
def get_the_playlists(date,offset):
    '''
    Get playlist ids for a particular day
    Inputs: date in ISO-8601 format
            offfset - page number
    Output: paired playlist ids with number of tracks
    '''
    return ([i['id'],i['snapshot_id'],i['tracks']['total']] for i in sp.featured_playlists(
        locale=None,
        country='US',
        timestamp=date,
        limit=50,
        offset=offset*50
    )['playlists']['items'])
    
def get_playlist_tracks(id_):
    '''
    Get the tracks for a spotify playlist.
    Input: playlist ID
    Output: list of song IDs
    '''
    return [i['track']['id'] for i in sp.user_playlist('spotify',id_)['tracks']['items']]

def get_song_features(ids):
    '''
    Get song features for each song in a list
    '''
    return pd.DataFrame(sp.audio_features(_)[0] for _ in ids)

def get_all_playlists():
    num_days = 1461 # that's 4 years
    start_date = datetime(2015,1,1,0,0)

    dates = ['T'.join(str(start_date + timedelta(hours=i*8)).split()) for i in range(int(num_days*3))]
    playlist_df = pd.DataFrame({0:[],1:[],2:[]})

    for date in tqdm_notebook(dates):
        while True:
            try:
                playlist_df = pd.concat([playlist_df,pd.DataFrame(list(get_the_playlists(date,0)))])
            except:
                time.sleep(30)
                continue
            break
    return playlist_df

def get_tune(search_string):
    attempts = 0
    while attempts < 3:
        try:
            return sp.search(user_df.iloc[0].search_string,type='track',limit=1)['tracks']['items'][0]['id']
        except:
            time.sleep(30)
            attempts += 1
            continue
        break
    return ''

In [302]:
#playlist_df = get_all_playlists()

In [77]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd
import seaborn as sns
from datetime import datetime, timedelta
from tqdm import tqdm, tqdm_notebook
import json
import time

datetime(2015,1,1,0,0)

datetime.datetime(2015, 1, 1, 0, 0)